metropolitan/HR/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from . import views

app_name='HR'
urlpatterns = [
    url(r'^$', views.index, name='main'),
    url(r'^display/',views.display ,name='displayHR'),
    url(r'^displayUser/',views.displayUser ,name='displayDetail'),
   # url(r'^(?P<pk>[-\w]+)/$',views.AttendanceDetailView.as_view(),name='detail')
    url(r'^attendance_detail/',views.search, name="attendance_detail")
 
]

metropolitan/invoice/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from invoice import views

app_name='invoice'
urlpatterns = [
    #path('catalog/', include('catalog.urls')),
    url(r'^Generate', views.invoice, name='invoice'),
    url(r'^pdf', views.pdf, name='pdf'),
    url(r'$', views.inv_opt, name='inv_opt'),
]

metropolitan/metropolitan/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from authenticate import views

urlpatterns = [
    url(r'^$',views.index, name='main'),
    #url(r'^first_app/',include('first_app.urls')),
  #  url(r'^basic_app/',include('basicapp.urls')),
    url(r'^task/',include('task.urls')),
    url(r'^HR/',include('HR.urls')),
    url(r'^authenticate/',include('authenticate.urls')),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^special/$',views.special, name='special'),
    url(r'^invoice/',include('invoice.urls')),
    url(r'^admin/', admin.site.urls),
]

metropolitan/task/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from task import views

app_name='task'
urlpatterns = [
    #path('catalog/', include('catalog.urls')),
    url(r'^$', views.tasks, name='tasks'),
    url(r'^display/',views.display ,name='display'),
    url(r'Assign/', views.assign,name='assign'),

]

metropolitan/HR/models.py
from django.db import models
from django.db import models
from authenticate.models import UserProfileInfo
from datetime import date

# Create your models here.
class Attendance1(models.Model):
    attendanceId = models.AutoField(primary_key=True)
    employee = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE, related_name='employee')  #default = request.user.is_authenticated
    date = models.DateField(default=date.today)
    timeIn = models.TimeField(auto_now=False, auto_now_add=False,null=True)
    timeOut = models.TimeField(auto_now=False, auto_now_add=False,null=True)
    status = models.CharField(max_length=1 , default = "N")
#test 3
    class Meta:
         unique_together = ('employee', 'date')

    def __str__(self):
        return self.employee.user.username

metropolitan/HR/forms.py
from django import forms
from django.contrib.auth.models import User
#from authenticate.models import UserProfileInfo
from HR.models import Attendance1
from datetime import date
from authenticate.models import UserProfileInfo


class DateInput(forms.DateInput):
     input_type = 'date'

class AttendanceForm(forms.ModelForm):
    end_date = forms.DateField(widget=DateInput())
    description = forms.CharField(widget=forms.Textarea)
    class Meta():
        model = Attendance1
        #testt
        fields = '_all_'    

metropolitan/HR/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
import datetime
from django.http import HttpResponse
from HR.models import Attendance1 # Create your views here.
from authenticate.models import UserProfileInfo
from django.contrib.auth.decorators import login_required
#from .forms import AttendanceForm
from django.contrib.auth.models import User



@login_required
def index(request):

    return render(request, 'HR/HRchoice.html', )

# Create your views here.
@login_required
def display(request):
    Attendances1 = Attendance1.objects.all()
    
    '''
    if request.method == "POST":
        data = request.POST.get("TaskID")
        task_ = Task.objects.get(taskId = int(data))
        task_.status = "C"
        task_.save()
        #print(data)
    '''
#    Tasks = Task.objects.order_by('end_date')
    users2 = UserProfileInfo.objects.order_by().distinct()
    attendance_list = []
    for attendance in Attendances1:
        attendance_list.append(attendance)
    #print(attendance_list)
    args = {"attendance_list" : attendance_list,"users":users2}
    return render(request, 'HR/HR_main.html', args)

@login_required
def displayUser(request):
    print('in display user')
    print(request.POST)

    if request.method == "POST":
        print('in POST')

        print(request.POST.get("employee"))
        username = request.POST.get("employee")
        attendance_ = Attendance1.objects.get(employee = username)
        args = {"attendance_list" : attendance_}

        return render(request, 'HR/detailview.html', args)

def search(request):
   # users = UserProfileInfo.objects.exclude(user = request.user)
    #creator = UserProfileInfo.objects.get(id = request.user.id)
    args = {}
    users2 = UserProfileInfo.objects.all()
    args = {"user_info" : users2}

    if request.method == "POST":
        print( request.POST)
        users2 = UserProfileInfo.objects.all()
        data = request.POST
        assignee_ = data.get("user")
        print(assignee_)
        
        for u in users2:
            if str(u.user)  == assignee_:
                id1 = u.id
                break
        assignee_ = Attendance1.objects.filter(employee = id1)
        profile = UserProfileInfo.objects.get(id = id1)
        print(assignee_)
        status =[]
        for i in assignee_:
            status.append(i.status)
        details_user=abscensce_counter(status)    
        args = {"user_info" : profile,"abscence":details_user[0],"late":details_user[1] }
        return render(request, 'HR/records.html', args)
    print(args)
    return render(request, 'HR/detail.html', args)
class AttendanceDetailView(DetailView):
    
    model = Attendance1
    def get_context_data(self, **kwargs):

        context = super(AttendanceDetailView, self).get_context_data(**kwargs)

        context['attendance_list'] = Attendance1.objects.all()
        return context

def abscensce_counter(l):
    details=[]
    counter = 0
    counter2 = 0
    for i in l:
        if i =="A":
            counter+=1
        if i=="L":
            counter2+=1
    details.append(counter)
    details.append(counter2)
    return details

metropolitan/templates/HR/HR_main.html
<!DOCTYPE html>
{%  load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Dashboard">
  <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
  <title>Attendance</title>

  <link rel="icon" type="image/png" href="{% static 'images/icons/logo.ico' %}">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!--external css-->
  <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
  <link href="{% static 'lib/advanced-datatable/css/demo_page.css' %}" rel="stylesheet" />
  <link href="{% static 'lib/advanced-datatable/css/demo_table.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'lib/advanced-datatable/css/DT_bootstrap.css' %}" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'libinv/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
  <link type="text/css" href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
  
    <link type="text/css" href="{% static 'images2/icons/css/font-awesome.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


   
  

  

  
  

</head>

<body>
  <section id="container">
   
    <header class="header black-bg" height="2">
     
      <ul class="nav pull-left top-menu">
        <li><a class="logout"  style="background-color:#2C3E50;  margin-top: 0px;  padding: 12.5px 20px; border: none #2C3E50 !important;" href="{% url 'invoice:inv_opt' %}"><i class="far fa-money-bill-alt fa-2x"></i></a></li>
        <li><a class="logout"  style="background-color:#2C3E50;margin-top: 0px;padding: 12.5px 20px; outline: none; border: solid #2C3E50 !important;" href="{% url 'main' %}    "><i class="fas fa-home fa-2x"></i>

        </a></li>
        <li><a class="logout" style="background-color:#2C3E50; margin-top: 0px; padding: 12.5px 10px; border: solid #2C3E50 !important;" href="{% url 'task:tasks' %}"> <i class="fas fa-tasks fa-2x"></i></a></li>
   
      
        
         
      </ul>
  
    <a href="{% url 'HR:main' %}"  class="logo" style="text-align:center-100px"><b style="text-align: center">Attendance</b></a>
    
    
    
    <div class="top-menu">
      <ul class="nav pull-right top-menu">
          <li><a class="logout"  style="margin-top: 10px;"  href="{% url 'logout' %}  ">Logout</a></li>
      </ul>

      <ul class="nav pull-right top-menu">
        <p class="logout1" style="color:white; margin-top: 12px; font-size:16px;">{{request.user.username|capfirst }}  </p>
      </ul>
    </div>
  </header>
    <!--header end-->
<!------------------------------------------------------------PAGE STARTS------------------------------------------------------------>
    <!--main content start-->
  
   
        
        <div class="row mb"></div>
          <!-- page start-->    <br><br>
          <div class="content-panel">  
            <div class="adv-table">   
              <table id="example" class="display" style="width:100%">
                <thead>
                  <tr>
                    <th>UserName</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Date</th>
                    <th>Time-In</th>
            		    <th>Time-Out</th>
                    <th>Status</th>

                  </tr>
                </thead>
                <tbody>
                {%for user in attendance_list %}
                  <form method="POST" action="."> 
                {% csrf_token %} 
                    <tr class="gradeA">
                      <td>{{user.employee}}</td>
                      <td>{{user.employee.first_name}}</td>
                      <td>{{user.employee.last_name}}</td>
                      <td>{{user.date}}</td>
                      <td>{{user.timeIn}}</td>
                      <td>{{user.timeOut}}</td>
                      <td>{{user.status}}</td>
                    </tr>
                 </form>
              {% endfor %}
                </tbody>
              </table>
			  
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
   
  </section>
  
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script class="include" type="text/javascript" src="{% static 'lib/jquery.dcjqaccordion.2.7.js' %}"></script>
  <script src="{% static 'lib/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'lib/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.dataTables.js' %}"></script>
  <script type="text/javascript" src="{% static 'lib/advanced-datatable/js/DT_bootstrap.js' %}"></script>
  <!--common script for all pages-->
  <script src="{% static 'lib/common-scripts.js' %}"></script>
  <!--script for this page-->
  <script type = "text/javascript">
  $(document).ready(function() {
    $('#example').DataTable();
} );
</script>
</body>

</html>

metropolitan/templates/HR/HRchoice.html
{%  load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HR</title>
<link rel="icon" type="image/png" href="{% static 'images/icons/logo.ico' %}">
<link type="text/css" href="{% static 'bootstrap2/css/bootstrap.min.css'%}" rel="stylesheet">
<link type="text/css" href="{% static 'x.css'%}" rel="stylesheet">
<link type="text/css" href="{% static 'images2/icons/css/font-awesome.css'%}" rel="stylesheet">
<link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
    rel='stylesheet'>
    <link type="text/css" href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


<script src="{% static 'bootstrap2/js/bootstrap.min.js'%}" type="text/javascript"></script>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" ></script>

<link href="{% static 'libinv/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

<link href="{% static 'libinv/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
<link href="{% static 'css/style.css' %}" rel="stylesheet">


</head>

<body>
    
    <section id="container" ></section>
   
        <header class="header black-bg" height="2">

          <ul class="nav pull-left top-menu">
            <li><a class="logout"  style="background-color:#2C3E50;  margin-top: 0px;  padding: 12.5px 20px; border: none #2C3E50 !important;" href="{% url 'invoice:inv_opt' %}"><i class="far fa-money-bill-alt fa-2x"></i></a></li>
            <li><a class="logout"  style="background-color:#2C3E50;margin-top: 0px;padding: 12.5px 20px; outline: none; border: solid #2C3E50 !important;" href="{% url 'main' %}    "><i class="fas fa-home fa-2x"></i>
    
            </a></li>
            <li><a class="logout" style="background-color:#2C3E50; margin-top: 0px; padding: 12.5px 10px; border: solid #2C3E50 !important;" href="{% url 'task:tasks' %}"> <i class="fas fa-tasks fa-2x"></i></a></li>
       
          
            
             
          </ul>
              
        
          <a href="" style="text-align:center" class="logo"><b>Human Resources</b></a>
          
          
          
          <div class="top-menu">
            <ul class="nav pull-right top-menu">
              <li><a class="logout" href="{% url 'logout' %}  ">Logout</a></li>
            </ul>

            <ul class="nav pull-right top-menu">
              <p class="logout1" style="color:white">{{request.user.username|capfirst }}  </p>
            </ul>
          </div>
        </header>

       
<!------------------------------------------------------DONEEEEEEEEEEE------------------------------------------->
<div class = "wrapper" style= "background: url({% static 'images2/bg.png'%}); " />


      
        <div class="wrapper">
            
            <div class="container">
               
                  
                    <div class="span9">
                        <div class="content">
                            <div class="btn-controls">
<br><br>
                               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <div class="btn-box-row row-fluid">

                                    <a href="{% url 'HR:displayHR' %}" class="btn-box big span4">  <br> <i class="icon-briefcase"></i>
                                    <p class="text-muted">
                                          <br>  Attendances</p>
                                         
                                          
                                    </a>
                                    
                                    <a href="{% url 'HR:attendance_detail' %}" class="btn-box big span4"> <br><i class="icon-list-alt"></i>
                                        <p class="text-muted">
                                           <br> Employee Records</p>
                                    </a>
                                   
                                   
                                
                                        
                                    </div>
                                    
                                
                                       
                                         
                     
                              
                                    <div style="width:500px;height:100px; "></div>
                                    <div style="width:500px;height:100px;"></div>
                                    <div style="width:500px;height:100px; "></div>
                                    <div style="width:500px;height:100px;"></div>
           
           
        </div>
       
        
        
    </body>
   

metropolitan/templates/HR/detail.html
{%  load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Metropolitan Security</title>
<link rel="icon" type="image/png" href="{% static 'images/icons/logo.ico' %}">
<link type="text/css" href="{% static 'bootstrap2/css/bootstrap.min.css'%}" rel="stylesheet">
<link type="text/css" href="{% static 'css2/theme.css'%}" rel="stylesheet">
<link type="text/css" href="{% static 'images2/icons/css/font-awesome.css'%}" rel="stylesheet">
<link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
    rel='stylesheet'>
    <link type="text/css" href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
    
 

<script src="{% static 'bootstrap2/js/bootstrap.min.js'%}" type="text/javascript"></script>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" ></script>

<link href="{% static 'libinv/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

<link href="{% static 'libinv/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<style type="text/css">
    html {
        overflow-y: hidden;
    }
    </style>

</head>

<body>
    
    <section id="container" ></section>
   
        <header class="header black-bg" height="2">
         
          
       
        
          <a href="{% url 'HR:main' %}"  class="logo" style="text-align:center-100px"><b>Attendance</b></a>
          
          
          
          <div class="top-menu">
            <ul class="nav pull-right top-menu">
                <li><a class="logout"  style="margin-top: 10px;"  href="{% url 'logout' %}  ">Logout</a></li>
            </ul>

            <ul class="nav pull-right top-menu">
              <p class="logout1" style="color:white; margin-top: 12px; font-size:16px;">{{request.user.username|capfirst }}  </p>
            </ul>
          </div>
        </header>

        <div class = "wrapper" style= "background: url({% static 'images2/bg.png'%}); " />

<!------------------------------------------------------DONEEEEEEEEEEE------------------------------------------->

        <!-- /navbar -->
        <div class="wrapper">
            
            <div class="container">


                    <div class="span9">
                        <div class="content">
                            <div class="btn-controls">
<br><br>
                               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <div class="btn-box-row row-fluid">
                                {%for user in user_info %}
                                <form id="form1" action="." method="post">
                                {% csrf_token %} 


                                
                                    
                                <a href="javascript:;" onclick="parentNode.submit();" class="btn-box big span4" id="employeeLink">  <br><i class="icon-user"></i>
                                    <p class="text-muted">
                                        
                                          <br>{{user}}</p>
                                          <input type="hidden" name="user" value={{user}}>
                                        </a>
                                    
                                


                                    
                                </form>
                                {% endfor %}
                                </div>

                                    </div>
                                    <div style="width:500px;height:100px;"></div>
                                    <div style="width:500px;height:100px;"></div>
                                    <div style="width:500px;height:100px;"></div>



</div>
                        </div>
</div>
        </div>


    </body>

        

metropolitan/templates/HR/records.html
<!DOCTYPE html>
{%  load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Dashboard">
  <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
  <title>Attendance</title>

  <link rel="icon" type="image/png" href="{% static 'images/icons/logo.ico' %}">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!--external css-->
  <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
  <link href="{% static 'lib/advanced-datatable/css/demo_page.css' %}" rel="stylesheet" />
  <link href="{% static 'lib/advanced-datatable/css/demo_table.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'lib/advanced-datatable/css/DT_bootstrap.css' %}" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'libinv/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
  <link type="text/css" href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
  
    <link type="text/css" href="{% static 'images2/icons/css/font-awesome.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


   
  

  

  
  

</head>

<body>
  <section id="container">
   
    <header class="header black-bg" height="2">
     
      <ul class="nav pull-left top-menu">
        <li><a class="logout"  style="background-color:#2C3E50;  margin-top: 0px;  padding: 12.5px 20px; border: none #2C3E50 !important;" href="{% url 'invoice:inv_opt' %}"><i class="far fa-money-bill-alt fa-2x"></i></a></li>
        <li><a class="logout"  style="background-color:#2C3E50;margin-top: 0px;padding: 12.5px 20px; outline: none; border: solid #2C3E50 !important;" href="{% url 'main' %}    "><i class="fas fa-home fa-2x"></i>

        </a></li>
        <li><a class="logout" style="background-color:#2C3E50; margin-top: 0px; padding: 12.5px 10px; border: solid #2C3E50 !important;" href="{% url 'task:tasks' %}"> <i class="fas fa-tasks fa-2x"></i><span class="badge" style="background-color:red;">3</span></a></li>
   
      
        
         
      </ul>
  
    <a href="index.html"  class="logo" style="text-align:center-100px"><b style="text-align: center">Attendance</b></a>
    
    
    
    <div class="top-menu">
      <ul class="nav pull-right top-menu">
          <li><a class="logout"  style="margin-top: 10px;"  href="{% url 'logout' %}  ">Logout</a></li>
      </ul>

      <ul class="nav pull-right top-menu">
        <p class="logout1" style="color:white; margin-top: 12px; font-size:16px;">{{request.user.username|capfirst }}  </p>
      </ul>
    </div>
  </header>
    <!--header end-->
<!------------------------------------------------------------PAGE STARTS------------------------------------------------------------>
    <!--main content start-->
  
   
        
        <div class="row mb"></div>
          <!-- page start-->    <br><br>
          <div class="content-panel">  
            <div class="adv-table">   
              <table id="example" class="display" style="width:100%">
                <thead>
                  <tr>
                    <th>UserName</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Total Abscences</th>
                    <th>Total Lateness</th>


                  </tr>
                </thead>
                <tbody>
                  <form method="POST" action="."> 
                {% csrf_token %} 
                    <tr class="gradeA">
                      <td>{{user_info}}</td>
                      <td>{{user_info.first_name}}</td>
                      <td>{{user_info.last_name}}</td>
                      <td>{{abscence}}</td>
                      <td>{{late}}</td>

                    </tr>
                 </form>
                </tbody>
              </table>
			  
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
   
  </section>
  
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script class="include" type="text/javascript" src="{% static 'lib/jquery.dcjqaccordion.2.7.js' %}"></script>
  <script src="{% static 'lib/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'lib/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.dataTables.js' %}"></script>
  <script type="text/javascript" src="{% static 'lib/advanced-datatable/js/DT_bootstrap.js' %}"></script>
  <!--common script for all pages-->
  <script src="{% static 'lib/common-scripts.js' %}"></script>
  <!--script for this page-->
  <script type = "text/javascript">
  $(document).ready(function() {
    $('#example').DataTable();
} );
</script>
</body>

</html>