metropolitan/HR/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from . import views

app_name='HR'
urlpatterns = [
    url(r'^$', views.index, name='main'),
    url(r'^display/',views.display ,name='displayHR'),
    url(r'^displayUser/',views.displayUser ,name='displayDetail'),
   # url(r'^(?P<pk>[-\w]+)/$',views.AttendanceDetailView.as_view(),name='detail')
    url(r'^attendance_detail/',views.search, name="attendance_detail")
 
]

metropolitan/invoice/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from invoice import views

app_name='invoice'
urlpatterns = [
    #path('catalog/', include('catalog.urls')),
    url(r'^Generate', views.invoice, name='invoice'),
    url(r'^pdf', views.pdf, name='pdf'),
    url(r'$', views.inv_opt, name='inv_opt'),
]

metropolitan/metropolitan/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from authenticate import views

urlpatterns = [
    url(r'^$',views.index, name='main'),
    #url(r'^first_app/',include('first_app.urls')),
  #  url(r'^basic_app/',include('basicapp.urls')),
    url(r'^task/',include('task.urls')),
    url(r'^HR/',include('HR.urls')),
    url(r'^authenticate/',include('authenticate.urls')),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^special/$',views.special, name='special'),
    url(r'^invoice/',include('invoice.urls')),
    url(r'^admin/', admin.site.urls),
]

metropolitan/task/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from task import views

app_name='task'
urlpatterns = [
    #path('catalog/', include('catalog.urls')),
    url(r'^$', views.tasks, name='tasks'),
    url(r'^display/',views.display ,name='display'),
    url(r'Assign/', views.assign,name='assign'),

]

metropolitan/invoice/forms.py
from django import forms
from django.forms import modelformset_factory, formset_factory
#from authenticate.models import UserProfileInfo
from invoice.models import Items, Address, Company, Invoice, invoice_items

#the fields attributes for forms.ModelFrom class will connect to our models
class Address_Form (forms.ModelForm):
    class Meta:
        model =Address
        fields = "__all__"
        widgets = {
            'street_name': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder':"Street"}),
            'city_name': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder':"City"}),
            'country_name': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder':"Country"}),
        }
        #1. fields = "__all__" # grab all fields
        #2. exclude = ["field1, field2"] #exclude those fields from model
        #3. fields = ("field1", "field1") #specify  the fields manually

class Company_Form (forms.ModelForm):
    class Meta:
        model =Company
        exclude = ["address_ID",'company_tel']
        widgets = {
            'company_name': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder':"Company"}),
            'company_email': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder':"Email"}),
        }
        #1. fields = "__all__" # grab all fields
        #2. exclude = ["field1, field2"] #exclude those fields from model
        #3. fields = ("field1", "field1") #specify  the fields manually

class Invoice_Form (forms.ModelForm):
    class Meta:
        model =Invoice
        fields = ("tax",)
        widgets = {
            'tax': forms.NumberInput(attrs={'class': 'form-control form-control-lg', 'min': '0', 'placeholder':"TAX Number"}),
        }
        #1. fields = "__all__" # grab all fields
        #2. exclude = ["field1, field2"] #exclude those fields from model
        #3. fields = ("field1", "field1") #specify  the fields manually

class Items_Form(forms.ModelForm):
    class Meta:
        model =Items
        fields = "__all__"
        widgets = {
            'itemcode': forms.NumberInput(attrs={'class': 'form-control form-control-lg', 'min': '0', 'placeholder':"Item Code"}),
            'item_name': forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder':"Item iterator"}),
            'itemprice': forms.NumberInput(attrs={'class': 'form-control form-control-lg', 'min': '0', 'placeholder':"Price"}),
            'item_desc': forms.NumberInput(attrs={'class': 'form-control form-control-lg', 'placeholder':"Description"}),
        }

class Invoice_items_Form(forms.ModelForm):
    class Meta:
        model =invoice_items
        fields = ("quantity",)
        widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'form-control form-control-lg', 'placeholder':"Quantity"}),
        }
class Itemss(forms.Form):
    itemcode = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control form-control-lg', 'min': '0', 'placeholder':"Item Code"}))
    item_name = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder':"Item name"}))
    item_desc = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-lg', 'placeholder':"Description"}))
    itemprice = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'form-control form-control-lg', 'min': '0', 'placeholder':"Price"}))
    quantity = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control form-control-lg', 'min': '0', 'placeholder':"Quantity"}))
ItemFormset = formset_factory(Itemss, extra=1)

'''ItemsFormset = modelformset_factory(
    Items,
    fields = "__all__",
    extra=1,
    widgets = {
            'itemcode': forms.NumberInput(attrs={'class': 'mmw form-control', 'placeholder':"Item Code"}),
            'item_name': forms.TextInput(attrs={'class': 'mmw1 form-control', 'placeholder':"Item iterator"}),
            'itemprice': forms.NumberInput(attrs={'class': 'mmw3 form-control', 'placeholder':"Price/unit"}),
        }
)
VTFormset = modelformset_factory(
    invoice_items,
    fields = ("quantity",),
    extra=2,
    widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'mmw2 form-control', 'placeholder':"Quantity"}),
        }
)'''
'''def add_ItemsFormset(InputSet: modelformset_factory):
    i = InputSet.total_form_count()
    newformset =  modelformset_factory(
    Items,
    fields = "__all__",
    extra=i+1,
    widgets = {
            'itemcode': forms.NumberInput(attrs={'class': 'mmw form-control', 'placeholder':"Item Code"}),
            'item_name': forms.TextInput(attrs={'class': 'mmw1 form-control', 'placeholder':"Item iterator"}),
            'itemprice': forms.NumberInput(attrs={'class': 'mmw3 form-control', 'placeholder':"Price/unit"}),
        }
    )
    newformset = newformset(queryset=Items.objects.none())
    field_old = []
    k=0
    for field in InputSet:
        field_old.append(field)
    for field in newformset:
        field = field_old[k]
        k+=1
        if k>=i:
            break
    return newformset'''

metropolitan/invoice/views.py
from django.shortcuts import render,redirect
from . import forms
from invoice.models import Items, Address, Company, Invoice, invoice_items
from django.forms import Form
from authenticate.models import UserProfileInfo
from datetime import datetime
from django.forms import modelformset_factory

from .forms import ItemFormset


def add_id(address_form:Form):
    street =address_form.cleaned_data["street_name"]
    city = address_form.cleaned_data["city_name"]
    country = address_form.cleaned_data["country_name"]
    incident = Address.objects.filter(street_name=street,city_name=city, country_name=country )
    if not incident:
        address_form.save()
        incident = Address.objects.filter(street_name=street,city_name=city, country_name=country )
    for i in incident:
        return i

def comp_id(company_form:Form, add: Form, telephone)-> Form:
    company_n = company_form.cleaned_data["company_name"]
    company_e = company_form.cleaned_data["company_email"]
    company_t = telephone
    incident = Company.objects.filter(address_ID = add, company_name= company_n, company_email=company_e, company_tel = company_t)
    if not incident:
        #company_form.save(commit=False)incident = Address.objects.filter(street_name=street,city_name=city, country_name=country )
        company = Company()
        company.address_ID = add
        company.company_name = company_n
        company.company_email = company_e
        company.company_tel = company_t
        company.save()
        incident = Company.objects.filter(address_ID = add, company_name= company_n, company_email=company_e, company_tel = company_t)
    for i in incident:
        return i

def inv_id(invoice_form:Form, cadd: Form, uadd: Form)-> Form:
    inv = Invoice()
    inv.creator = uadd
    inv.companey_ID = cadd
    inv.tax = invoice_form.cleaned_data["tax"]
    inv.save()
    user1 = Invoice.objects.get(invoiceId = inv.invoiceId)
    return user1
    

def invoice(request):
    if request.method =='POST':
        #Header
        address_form = forms.Address_Form(request.POST, prefix="address_form" )
        company_form = forms.Company_Form(request.POST, prefix="company_form")
        invoice_form = forms.Invoice_Form(request.POST, prefix="invoice_form")
        #Items
        formset = ItemFormset(request.POST)
        print(formset.errors)
        telephone = request.POST.get("telNum")
        if request.POST.get("adddd"):
            render(request, 'invoice/invoice.html',{'formset':formset,'address_form': address_form, "company_form":company_form, "invoice_form":invoice_form} )
        else:
            if address_form.is_valid() and company_form.is_valid() and invoice_form.is_valid() and formset.is_valid():
                print("DONEEE")
                print("Company name: ",company_form.cleaned_data["company_name"])
                print("Company email: ",company_form.cleaned_data["company_email"])
                print("Company tel: ",telephone)
                print("Tax : ",invoice_form.cleaned_data["tax"])
                print("Street : ",address_form.cleaned_data["street_name"])
                print("City : ",address_form.cleaned_data["city_name"])
                print("Country : ",address_form.cleaned_data["country_name"])
                print("username : ", request.user.username)
                ############ User db
                users2 = UserProfileInfo.objects.all()
                id2 = 0
                for u in users2:
                    if str(u.user)  == request.user.username:
                        id2 = u.id
                assignee_instance = UserProfileInfo.objects.get(id = id2)
                #Check in Address db; if (street city country) name combination exist, else add one, and return the id return address_id
                address_instance= add_id(address_form)
                #Check in Company db; if (company name, address_id) exists, else add one and return company_id
                company_instance= comp_id(company_form, address_instance, telephone)
                #Insertto invoice db; using companyid and userid, return invoice_id
                invoice_instance= inv_id(invoice_form, company_instance, assignee_instance)
                #Loop over items
                c =[]
                i=0
                for form in formset:
                    #Check in items db; if item code not exist, create one
                    item_instance=""
                    #print(form.cleaned_data["itemcode"])
                    incident = Items.objects.filter(itemcode=form.cleaned_data.get('itemcode'))
                    if incident:
                        print("\nItem of code: {} already exist with name = {} and price = {}".format(form.cleaned_data.get('itemcode'),form.cleaned_data.get("item_name"),form.cleaned_data.get("itemprice")))
                        print("they'll be updated according to the input")
                        incident.update(item_name=form.cleaned_data.get("item_name"), itemprice=form.cleaned_data.get("itemprice"),item_desc = form.cleaned_data.get('item_desc'))
                    else:
                            itemm = Items()
                            itemm.item_name=form.cleaned_data.get("item_name")
                            itemm.itemcode=form.cleaned_data.get('itemcode')
                            itemm.itemprice = form.cleaned_data.get('itemprice')
                            itemm.item_desc = form.cleaned_data.get('item_desc')
                            print("\nAdded new Item of code: {} name = {} and price = {}".format(form.cleaned_data.get('itemcode'),form.cleaned_data.get("item_name"),form.cleaned_data.get("itemprice")))
                            itemm.save()
                    item_instance = Items.objects.get(itemcode=form.cleaned_data.get("itemcode"))
                    #Insert to invoice_items db; itemcode, invoice_id ....
                    inv_it = invoice_items()
                    inv_it.itemcode = item_instance
                    inv_it.invoiceId = invoice_instance
                    inv_it.quantity = form.cleaned_data.get("quantity")
                    inv_it.save()
                return pdf(request, invoice_instance.invoiceId)
    else:
        address_form = forms.Address_Form(prefix="address_form")
        company_form = forms.Company_Form(prefix="company_form")
        invoice_form = forms.Invoice_Form(prefix="invoice_form")
        formset = ItemFormset(request.GET or None)
    return render(request, 'invoice/invoice.html',{'formset':formset,'address_form': address_form, "company_form":company_form, "invoice_form":invoice_form} )
def inv_opt(request):
    return render(request, 'invoice/options.html')
def pdf(request, invoice_id=None ):
    invalid=""
    if request.POST:
        if invoice_id:
            invoice_id=invoice_id
        elif request.POST.get('inv_id'):
            invoice_id=request.POST.get('inv_id')
        try:
            invoice = Invoice.objects.get(invoiceId = invoice_id)
            company=invoice.companey_ID.company_name
            company_email=invoice.companey_ID.company_email
            company_tel=invoice.companey_ID.company_tel
            street=invoice.companey_ID.address_ID.street_name
            city=invoice.companey_ID.address_ID.city_name
            country=invoice.companey_ID.address_ID.country_name
            invoicenum = invoice.invoiceId
            date = invoice.invoicedate
            tax = invoice.tax
            name=invoice.creator.user.username
            inv_it = invoice_items.objects.filter(invoiceId =invoice)
            ll=[]
            index=1
            total=0
            for i in inv_it:
                item_list=[]
                item_list.append(index)
                index=index+1
                item_list.append(int(i.itemcode.itemcode))
                item_list.append(i.itemcode.item_name)
                item_list.append(i.itemcode.itemprice)
                item_list.append(int(i.quantity))
                total=total+i.itemcode.itemprice * i.quantity
                item_list.append(i.itemcode.itemprice * i.quantity)
                item_list.append(i.itemcode.item_desc)
                ll.append(item_list)
            print(ll)
            print(total)
            tax=round(total*(tax/100.0),2)
            print(tax)
            t = round(total-tax,2)
            print(t)
            print(company_tel)
            return render(request, 'invoice/pdf.html', {'name':name,'t':t,'total':total,'tax':tax,'company':company,'company_tel':company_tel,'company_email':company_email,'street':street,'city':city,'country':country, 'invoicenum':invoicenum, 'date': date, 'list':ll})
        except:
            invalid = "Invalid Invoice ID"
            
    invoice = Invoice.objects.all()
    ll=[]
    for i in invoice:
        item_list=[]
        item_list.append(i.companey_ID.company_name)
        item_list.append(i.invoicedate)
        item_list.append(i.creator.user.username)
        item_list.append(i.invoiceId)
        ll.append(item_list)
    return render(request, 'invoice/search.html', {'list':ll,"invalid":invalid})

metropolitan/templates/invoice/options.html
{%  load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">

  <title>Invoice</title>
<link rel="icon" type="image/png" href="{% static 'images/icons/logo.ico' %}">
<link type="text/css" href="{% static 'bootstrap2/css/bootstrap.min.css'%}" rel="stylesheet">
<link type="text/css" href="{% static 'x.css'%}" rel="stylesheet">
<link type="text/css" href="{% static 'images2/icons/css/font-awesome.css'%}" rel="stylesheet">
<link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
    rel='stylesheet'>
    <link type="text/css" href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
 

<script src="{% static 'bootstrap2/js/bootstrap.min.js'%}" type="text/javascript"></script>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" ></script>

<link href="{% static 'libinv/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

<link href="{% static 'libinv/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


</head>

<body>
    
    <section id="container" ></section>
   
    <header class="header black-bg" height="2">
       
      
        <ul class="nav pull-left top-menu">
            <li><a class="logout"  style="background-color:#2C3E50;  margin-top: 0px;  padding: 12.5px 20px; border: none #2C3E50 !important;" href="{% url 'HR:displayHR' %}"><i class="fas fa-user fa-2x"></i></a></li>
            <li><a class="logout"  style="background-color:#2C3E50;margin-top: 0px;padding: 12.5px 20px; outline: none; border: solid #2C3E50 !important;" href="{% url 'main' %}  "><i class="fas fa-home fa-2x"></i>

            </a></li>
            <li><a class="logout" style="background-color:#2C3E50; margin-top: 0px; padding: 12.5px 10px; border: solid #2C3E50 !important;" href="{% url 'task:tasks' %}"> <i class="fas fa-tasks fa-2x"></i></a></li>
       
          
           
        </ul>
    
      <a href="index.html"  class="logo" ><b>Invoice</b></a>
      
      
      
      <div class="top-menu">
        <ul class="nav pull-right top-menu">
            <li><a class="logout"  style="margin-top: 10px;"  href="{% url 'logout' %}  ">Logout</a></li>
        </ul>

        <ul class="nav pull-right top-menu">
          <p class="logout1" style="color:white; margin-top: 12px; font-size:16px;">{{request.user.username|capfirst }}  </p>
        </ul>
      </div>
    </header>

       
<!------------------------------------------------------DONEEEEEEEEEEE------------------------------------------->
<div class = "wrapper" style= "background: url({% static 'images2/bg.png'%}); " />


      
        <div class="wrapper">
            
            <div class="container">
               
                  
                    <div class="span9">
                        <div class="content">
                            <div class="btn-controls">
<br><br>
                               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <div class="btn-box-row row-fluid">

                                <a href="{% url 'invoice:invoice' %}" class="btn-box big span4">  <br><i class="fas fa-file-invoice-dollar"></i>
                                    <p class="text-muted">
                                          <br>  Generate Invoice</p>
                                          
                                    </a>
                                    
                                    <a href="{% url 'invoice:pdf' %}" class="btn-box big span4"> <br><i class="icon-search"></i>
                                        <p class="text-muted">
                                           <br> Search Invoice</p>
                                    </a>
                                   
                                   
                                
                                        
                                    </div>
                                    
                                
                                       
                                         
                     
                                    <div style="width:500px;height:100px; "></div>
                                    <div style="width:500px;height:100px;"></div>

                                    <div style="width:500px;height:100px; "></div>
                                    <div style="width:500px;height:100px;"></div>
           
        </div>
       
        
        
    </body>

metropolitan/templates/invoice/search.html
<!DOCTYPE html>
{%  load static %}

<html lang="en">

<head>
  <meta charset="utf-8">

  <title>Search Invoice</title>


  <!-- Bootstrap core CSS -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!--external css-->
  <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
  <link href="{% static 'lib/advanced-datatable/css/demo_page.css' %}" rel="stylesheet" />
  <link href="{% static 'lib/advanced-datatable/css/demo_table.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'lib/advanced-datatable/css/DT_bootstrap.css' %}" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


</head>

<body>
  <section id="container">
   
    <header class="header black-bg" height="2">
    
    
      <ul class="nav pull-left top-menu">
        <li><a class="logout"  style="background-color:#2C3E50;  margin-top: 0px;  padding: 12.5px 20px; border: none #2C3E50 !important;" href="{% url 'HR:displayHR' %}"><i class="fas fa-user fa-2x"></i></a></li>
        <li><a class="logout"  style="background-color:#2C3E50;margin-top: 0px;padding: 12.5px 20px; outline: none; border: solid #2C3E50 !important;" href="{% url 'main' %}  "><i class="fas fa-home fa-2x"></i>

        </a></li>
        <li><a class="logout" style="background-color:#2C3E50; margin-top: 0px; padding: 12.5px 10px; border: solid #2C3E50 !important;" href="{% url 'task:tasks' %}"> <i class="fas fa-tasks fa-2x"></i></a></li>
   
      
        
         
      </ul>
  
    <a href="index.html"  class="logo" style="text-align:center-100px"><b>Search Invoice</b></a>
    
    
    
    <div class="top-menu">
      <ul class="nav pull-right top-menu">
          <li><a class="logout"  style="margin-top: 10px;"  href="{% url 'logout' %}  ">Logout</a></li>
      </ul>

      <ul class="nav pull-right top-menu">
        <p class="logout1" style="color:white; margin-top: 12px; font-size:16px;">{{request.user.username|capfirst }}  </p>
      </ul>
    </div>
  </header>
    <!--header end-->
<!------------------------------------------------------------PAGE STARTS------------------------------------------------------------>
    <!--main content start-->
  
     <br><br>
        <div class="row mb"></div>
          <!-- page start-->    <br><br>
          <form method="POST">{% csrf_token %}

        <div class = 'form-group col-md-2'>
            <ul class="errorlist" style="color:red"> {{ invalid }}</ul>
            <input  type="number" id="inv_id" name="inv_id" min="0" class= 'form-control form-control-lg' placeholder="Invoice ID">
        </div>
        <input type="submit"  style="position:relative !important; left:50px; top:10px !important;" class ='btn btn-primary' value="View Invoice" id="submit" name="submit">

    </form>
        <br><br>
        <br><br>
          <div class="content-panel">  
            <div class="adv-table">   
              <table id="example" class="display" style="width:100%">
                <thead>
                  <tr>
                    <th>Company Name </th>
                    <th>Date </th>
                    <th>Creator </th>
                    <th>Invoice Id</th>
                  </tr>
                </thead>
                <tbody>
                {% for l in list %} 
                  <tr class="gradeX">
                    <td>{{ l.0 }}</td>
                    <td>{{ l.1 }}</td>
                    <td class="hidden-phone">{{ l.2 }}</td>
                    <td class="center hidden-phone">{{ l.3 }}</td>
                  </tr>
                {% endfor %}  
                </tbody>
              </table>
			  
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
   
  </section>
  
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script class="include" type="text/javascript" src="{% static 'lib/jquery.dcjqaccordion.2.7.js' %}"></script>
  <script src="{% static 'lib/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'lib/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.dataTables.js' %}"></script>
  <script type="text/javascript" src="{% static 'lib/advanced-datatable/js/DT_bootstrap.js' %}"></script>
  <!--common script for all pages-->
  <script src="{% static 'lib/common-scripts.js' %}"></script>
  <!--script for this page-->
  <script type="text/javascript">
    /* 
delete all rows 
 $(document).ready(function() {
    $('#example').DataTable();
$(".example").append('
 		<tr class="gradeA">
                    <td>Trident</td>
                    <td>Internet Explorer 4.0</td>
                    <td>95+</td>
                    <td> 4</td>
                    <td >X</td>
                  </tr> ')

} );




 */
   

   $(document).ready(function() {
    $('#example').DataTable();
} );

     
  </script>
</body>

</html>