metropolitan/HR/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from . import views

app_name='HR'
urlpatterns = [
    url(r'^$', views.index, name='main'),
    url(r'^display/',views.display ,name='displayHR'),
    url(r'^displayUser/',views.displayUser ,name='displayDetail'),
   # url(r'^(?P<pk>[-\w]+)/$',views.AttendanceDetailView.as_view(),name='detail')
    url(r'^attendance_detail/',views.search, name="attendance_detail")
 
]

metropolitan/invoice/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from invoice import views

app_name='invoice'
urlpatterns = [
    #path('catalog/', include('catalog.urls')),
    url(r'^Generate', views.invoice, name='invoice'),
    url(r'^pdf', views.pdf, name='pdf'),
    url(r'$', views.inv_opt, name='inv_opt'),
]

metropolitan/metropolitan/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from authenticate import views

urlpatterns = [
    url(r'^$',views.index, name='main'),
    #url(r'^first_app/',include('first_app.urls')),
  #  url(r'^basic_app/',include('basicapp.urls')),
    url(r'^task/',include('task.urls')),
    url(r'^HR/',include('HR.urls')),
    url(r'^authenticate/',include('authenticate.urls')),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^special/$',views.special, name='special'),
    url(r'^invoice/',include('invoice.urls')),
    url(r'^admin/', admin.site.urls),
]

metropolitan/task/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from task import views

app_name='task'
urlpatterns = [
    #path('catalog/', include('catalog.urls')),
    url(r'^$', views.tasks, name='tasks'),
    url(r'^display/',views.display ,name='display'),
    url(r'Assign/', views.assign,name='assign'),

]

metropolitan/task/models.py
from django.db import models
from datetime import date
from authenticate.models import UserProfileInfo
from datetime import datetime
# Create your models here.
class Task(models.Model):
    creator = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE, related_name='creator'  ) #default = request.user.is_authenticated
    taskId = models.AutoField(primary_key=True)
    assignee  = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE, related_name='assignee')
    description = models.CharField(max_length=400)
    start_date = models.DateField(default=datetime.now)
    end_date = models.DateField()
    status = models.CharField(max_length=1 , default = "I")
#test 2
#test 3
    def __str__(self):
        return str(self.taskId)

metropolitan/task/forms.py
from django import forms
from django.contrib.auth.models import User
#from authenticate.models import UserProfileInfo
from task.models import Task
from datetime import date
from authenticate.models import UserProfileInfo


class DateInput(forms.DateInput):
     input_type = 'date'

class TaskForm(forms.ModelForm):
    end_date = forms.DateField(widget=DateInput())
    description = forms.CharField(widget=forms.Textarea)
    class Meta():
        model = Task
        #testt
        fields = ("assignee","description","end_date","creator")
    

metropolitan/task/views.py
from django.shortcuts import render
import datetime
from django.http import HttpResponse
from task.models import Task # Create your views here.
from authenticate.models import UserProfileInfo
from django.contrib.auth.decorators import login_required
from .forms import TaskForm
from django.contrib.auth.models import User

@login_required
def tasks(request):

    return render(request, 'task/tasks.html', )


def assign(request):
    data = request.POST
    print(request.user)
    users = UserProfileInfo.objects.exclude(user = request.user)
    print("done")
    #creator = UserProfileInfo.objects.get(id = request.user.id)
    if request.method == "POST":
        users2 = UserProfileInfo.objects.all()
        data = request.POST
        end_date = data.get("end_date")
        assignee_ = data.get("dropdown")
        id1 = 0
        id2 = 0
        for u in users2:
            if str(u.user)  == assignee_:
                id1 = u.id
            elif str(u.user)  == request.user.username:
                id2 = u.id
        assignee = UserProfileInfo.objects.get(id = id1)
        creator = UserProfileInfo.objects.get(id = id2)
        description = data.get("description")
        creator = creator
        print(creator.user ,"of id :", id2 ,assignee_ , "of id :" , id1)
        Task.objects.create(end_date = end_date ,description = description ,status = "I" ,assignee = assignee , creator = creator)
        return render(request, 'task/tasks.html', {'users':users})
    return render(request, 'task/assign.html', {'users':users})
#test3
@login_required
def display(request):
    Tasks1 = Task.objects.all()
    if request.method == "POST":
        data = request.POST.get("TaskID")
        task_ = Task.objects.get(taskId = int(data))
        task_.status = "C"
        task_.save()
        #print(data)
    Tasks = Task.objects.order_by('end_date')
    task_list = []
    for task in Tasks:
        if str(task.assignee) == request.user.username and str(task.status) == "I": 
            task_list.append(task)
    args = {"task_list" : task_list}
    return render(request, 'task/display.html', args)

metropolitan/templates/task/assign.html
<!DOCTYPE html>
{%  load static %}
<html lang="en">

<head>
 <link href="{% static 'taskassigncss/style.css'%}" rel="stylesheet">
   <body style="background-color: #2C3E50 ;"></body>
   <main>
    <div style="background-color: white ;" id="left">
      <div id="form-wrapper">
       
        
        <form method="POST" action=".">     

          <input class="submit-button" type="submit" value="Assign"></input>
          <h1>Add Task</h1>
          <h3>Task Description</h3>
          <textarea name="description"rows="2" cols="2" placeholder="Write a new task here." required></textarea>
          <div id="form-col-wrapper">
            <div id="form-left">
               
              <h3>Due Date:</h3>
            
<input type="date"  name="end_date" />
<br>
            </div>
            <div id="form-right">
                {% csrf_token %}   
              <h3>Assign To:</h3>
              <select name = "dropdown">
                   


{%for user in users%}
  <option value = {{user.user}}> {{user.user}}</option>
{% endfor %}
                  
                </select>
            </div>
    <div class="form-footer"></div>
          </div>
         
        </form>
      </div>
    </div>
   
  </main>
 
</body>

</html>

metropolitan/templates/task/display.html
<!DOCTYPE html>
{%  load static %}

<html lang="en">

<head>
  <meta charset="utf-8">

  <title>My Tasks</title>
  <link rel="icon" type="image/png" href="{% static 'images/icons/logo.ico' %}">


  <!-- Bootstrap core CSS -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!--external css-->
  <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
  <link href="{% static 'lib/advanced-datatable/css/demo_page.css' %}" rel="stylesheet" />
  <link href="{% static 'lib/advanced-datatable/css/demo_table.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'lib/advanced-datatable/css/DT_bootstrap.css' %}" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'libinv/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
  <link type="text/css" href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
  
    <link type="text/css" href="{% static 'images2/icons/css/font-awesome.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  

  

  
  

</head>

<body>
  <section id="container">
   
    <header class="header black-bg" height="2">
     
      <ul class="nav pull-left top-menu">
        <li><a class="logout"  style="background-color:#2C3E50;  margin-top: 0px;  padding: 12.5px 20px; border: none #2C3E50 !important;" href="{% url 'invoice:inv_opt' %}"><i class="far fa-money-bill-alt fa-2x"></i></a></li>
        <li><a class="logout"  style="background-color:#2C3E50;margin-top: 0px;padding: 12.5px 20px; outline: none; border: solid #2C3E50 !important;" href="{% url 'main' %}    "><i class="fas fa-home fa-2x"></i>

        </a></li>
        <li><a class="logout" style="background-color:#2C3E50; margin-top: 0px; padding: 12.5px 10px; border: solid #2C3E50 !important;" href="{% url 'task:tasks' %}"> <i class="fas fa-user fa-2x"></i></span></a></li>
   
      
        
         
      </ul>
  
    <a href="index.html"  class="logo" style="text-align:center-100px"><b style="text-align: center">My Tasks</b></a>
    
    
    
    <div class="top-menu">
      <ul class="nav pull-right top-menu">
          <li><a class="logout"  style="margin-top: 10px;"  href="{% url 'logout' %}  ">Logout</a></li>
      </ul>

      <ul class="nav pull-right top-menu">
        <p class="logout1" style="color:white; margin-top: 12px; font-size:16px;">{{request.user.username|capfirst }}  </p>
      </ul>
    </div>
  </header>
    <!--header end-->
<!------------------------------------------------------------PAGE STARTS------------------------------------------------------------>
    <!--main content start-->
  
  
   
   
        
        <div class="row mb"></div>
          <!-- page start-->    <br><br>
          <div class="content-panel">  
            <div class="adv-table">   
              <table id="example" class="display" style="width:100%">
                
                <thead>
                  <tr>
                    <th >Description</th>
    <th >Due Date </th>
    <th >Creator</th>
    <th >Status</th>

                  </tr>
                </thead>
                <tbody>
                  {%for task in task_list %}
                  <form method="POST" action="."> 
                  {% csrf_token %}
                  
                    <tr class="gradeA">
                     
                        <td>{{task.description}}</td>
                        <td>{{task.end_date}}</td>
                        <td>{{task.creator}}</td>
                        <td><button name="TaskID" type="submit" class="btn btn-success" value={{task}}>Mark As Completed &nbsp; <i class="fas fa-check"></i></button>
                        </td>
                        
                      
                    </tr>
                 </form>
              {% endfor %}
                </tbody>
              </table>
			  
            </div>
          </div>
          <!-- page end-->
        </div>
        <!-- /row -->
      </section>
      <!-- /wrapper -->
    </section>
   
  </section>
  
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <script class="include" type="text/javascript" src="{% static 'lib/jquery.dcjqaccordion.2.7.js' %}"></script>
  <script src="{% static 'lib/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'lib/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <script type="text/javascript" language="javascript" src="{% static 'lib/advanced-datatable/js/jquery.dataTables.js' %}"></script>
  <script type="text/javascript" src="{% static 'lib/advanced-datatable/js/DT_bootstrap.js' %}"></script>
  <!--common script for all pages-->
  <script src="{% static 'lib/common-scripts.js' %}"></script>
  <!--script for this page-->
 
  
</body>

</html>

metropolitan/templates/task/tasks.html
{%  load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">

  <title>Tasks</title>
<link rel="icon" type="image/png" href="{% static 'images/icons/logo.ico' %}">
<link type="text/css" href="{% static 'bootstrap2/css/bootstrap.min.css'%}" rel="stylesheet">
<link type="text/css" href="{% static 'x.css'%}" rel="stylesheet">
<link type="text/css" href="{% static 'images2/icons/css/font-awesome.css'%}" rel="stylesheet">
<link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
    rel='stylesheet'>
    <link type="text/css" href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
 

<script src="{% static 'bootstrap2/js/bootstrap.min.js'%}" type="text/javascript"></script>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" ></script>

<link href="{% static 'libinv/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

<link href="{% static 'libinv/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


</head>

<body>
    
    <section id="container" ></section>
   
    <header class="header black-bg" height="2">
     
    
      <ul class="nav pull-left top-menu">
        <li><a class="logout"  style="background-color:#2C3E50;  margin-top: 0px;  padding: 12.5px 20px; border: none #2C3E50 !important;" href="{% url 'HR:displayHR' %}"><i class="fas fa-user fa-2x"></i></a></li>
        <li><a class="logout"  style="background-color:#2C3E50;margin-top: 0px;padding: 12.5px 20px; outline: none; border: solid #2C3E50 !important;" href="{% url 'main' %}   "><i class="fas fa-home fa-2x"></i>
  
        </a></li>
        <li><a class="logout" style="background-color:#2C3E50; margin-top: 0px; padding: 12.5px 10px; border: solid #2C3E50 !important;" href="{% url 'invoice:inv_opt' %}"> <i class="far fa-money-bill-alt fa-2x"></i></a></li>
   
        
         
      </ul>
  
    <a href="index.html"  class="logo" style="text-align:center-100px"><b>TASKS</b></a>
    
    
    
    <div class="top-menu">
      <ul class="nav pull-right top-menu">
          <li><a class="logout"  style="margin-top: 10px;"  href="{% url 'logout' %}  ">Logout</a></li>
      </ul>

      <ul class="nav pull-right top-menu">
        <p class="logout1" style="color:white; margin-top: 12px; font-size:16px;">{{request.user.username|capfirst }}  </p>
      </ul>
    </div>
  </header>

       
<!------------------------------------------------------DONEEEEEEEEEEE------------------------------------------->
<div class = "wrapper" style= "background: url({% static 'images2/bg.png'%}); " />


      
        <div class="wrapper">
            
            <div class="container">
               
                  
                    <div class="span9">
                        <div class="content">
                            <div class="btn-controls">
<br><br>
                               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <div class="btn-box-row row-fluid">

                                    <a href="{% url 'task:display' %}" class="btn-box big span4">  <br><i class="fas fa-portrait"></i>
                                    <p class="text-muted">
                                          <br>  My Tasks</p>
                                          
                                    </a>
                                    
                                    <a href="{% url 'task:assign' %}" class="btn-box big span4"> <br><i class="icon-list"></i>
                                        <p class="text-muted">
                                           <br> Assign Task</p>
                                    </a>
                                   
                                   
                                
                                        
                                    </div>
                                    
                                
                                       
                                         
                                    <div style="width:500px;height:100px; "></div>
                                    <div style="width:500px;height:100px;"></div>

                              
                                    <div style="width:500px;height:100px; "></div>
                                    <div style="width:500px;height:100px;"></div>
           
        </div>
       
        
        
    </body>
   