metropolitan/HR/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from . import views

app_name='HR'
urlpatterns = [
    url(r'^$', views.index, name='main'),
    url(r'^display/',views.display ,name='displayHR'),
    url(r'^displayUser/',views.displayUser ,name='displayDetail'),
   # url(r'^(?P<pk>[-\w]+)/$',views.AttendanceDetailView.as_view(),name='detail')
    url(r'^attendance_detail/',views.search, name="attendance_detail")
 
]

metropolitan/authenticate/urls.py
from django.conf.urls import url
from authenticate import views

app_name='authenticate'
urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^register/', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),

] 

metropolitan/invoice/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from invoice import views

app_name='invoice'
urlpatterns = [
    #path('catalog/', include('catalog.urls')),
    url(r'^Generate', views.invoice, name='invoice'),
    url(r'^pdf', views.pdf, name='pdf'),
    url(r'$', views.inv_opt, name='inv_opt'),
]

metropolitan/metropolitan/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from authenticate import views

urlpatterns = [
    url(r'^$',views.index, name='main'),
    #url(r'^first_app/',include('first_app.urls')),
  #  url(r'^basic_app/',include('basicapp.urls')),
    url(r'^task/',include('task.urls')),
    url(r'^HR/',include('HR.urls')),
    url(r'^authenticate/',include('authenticate.urls')),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^special/$',views.special, name='special'),
    url(r'^invoice/',include('invoice.urls')),
    url(r'^admin/', admin.site.urls),
]

metropolitan/task/urls.py
# Use include() to add paths from the catalog application 
from django.conf.urls import url
from task import views

app_name='task'
urlpatterns = [
    #path('catalog/', include('catalog.urls')),
    url(r'^$', views.tasks, name='tasks'),
    url(r'^display/',views.display ,name='display'),
    url(r'Assign/', views.assign,name='assign'),

]

metropolitan/templates/login.html
<!DOCTYPE html>
{%  load static %}

<html lang="en">

<head>
	<title>Metropolitan Security</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!--===========================================ICON====================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/logo.ico' %}">
	<link rel="stylesheet" type="text/css" href="{%  static 'vendor/bootstrap/css/bootstrap.min.css'%}">

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=" {% static 'css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">
    <!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js'%}"></script>
<!--===============================================================================================-->
</head>
<body style="background-color: #517195;">
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form action="{% url 'authenticate:user_login' %}" method="POST" class="login100-form validate-form">
					{% csrf_token %}

					{{ user_form.as_p}}
					{{ profile_form.as_p }}
					
					
					<div class="wrap-input100 validate-input" >
						<input class="input100" type="text" name="username">
						<span class="focus-input100"></span>
						<span class="label-input100">Username</span>
					</div>
					
					
					<div class="wrap-input100 validate-input" >
						<input class="input100" type="password" name="password">
						<span class="focus-input100"></span>
						<span class="label-input100">Password</span>
					</div>


					
			
					<script type = "text/javascript">
						$(document).ready(function () {
						
						
						
						
						
							$('.input100').each(function(){
								$(this).on('blur', function(){
									if($(this).val().trim() != "") {
										$(this).addClass('has-val');
									}
									else {
										$(this).removeClass('has-val');
									}
								})
							})
						
						
							/*==================================================================
							[ Validate ]*/
							var input = $('.validate-input .input100');
						
							$('.validate-form').on('submit',function(){
								var check = true;
						
								for(var i=0; i<input.length; i++) {
									if(validate(input[i]) == false){
										showValidate(input[i]);
										check=false;
									}
								}
						
								return check;
							});
						
						
							$('.validate-form .input100').each(function(){
								$(this).focus(function(){
								   hideValidate(this);
								});
							});
						
							function validate (input) {
								if($(input).attr('type') == 'email' || $(input).attr('name') == 'email') {
									if($(input).val().trim().match(/^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{1,5}|[0-9]{1,3})(\]?)$/) == null) {
										return false;
									}
								}
								else {
									if($(input).val().trim() == ''){
										return false;
									}
								}
							}
						
							function showValidate(input) {
								var thisAlert = $(input).parent();
						
								$(thisAlert).addClass('alert-validate');
							}
						
							function hideValidate(input) {
								var thisAlert = $(input).parent();
						
								$(thisAlert).removeClass('alert-validate');
							}
						
						});
						
						
						
						  </script>
						
					<div class="container-login100-form-btn">
						<button type="submit" class="btn btn-secondary btn-lg btn-block"> Login </button>
					</div>
					
					<div class="text-center p-t-46 p-b-20">
						
					</div>

					
				</form>

				<div class="login100-more" style="background:url(http://www.notaclinic.com/wp-content/uploads/2017/07/METROPOLITAN-2.jpg)";></div>
				</div>
			</div>
		</div>
	</div>
	
	



</body>
</html>

metropolitan/templates/main2.html
{%  load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Metropolitan Security</title>
<link rel="icon" type="image/png" href="{% static 'images/icons/logo.ico' %}">
<link type="text/css" href="{% static 'bootstrap2/css/bootstrap.min.css'%}" rel="stylesheet">
<link type="text/css" href="{% static 'css2/theme.css'%}" rel="stylesheet">
<link type="text/css" href="{% static 'images2/icons/css/font-awesome.css'%}" rel="stylesheet">
<link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
    rel='stylesheet'>
    <link type="text/css" href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
    
 

<script src="{% static 'bootstrap2/js/bootstrap.min.js'%}" type="text/javascript"></script>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" ></script>

<link href="{% static 'libinv/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

<link href="{% static 'libinv/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<style type="text/css">
    html {
        overflow-y: hidden;
    }
    </style>

</head>

<body>
    
    <section id="container" ></section>
   
        <header class="header black-bg" height="2">
         
          
       
        
          <a href="index.html"  class="logo" style="text-align:center-100px"><b>Home</b></a>
          
          
          
          <div class="top-menu">
            <ul class="nav pull-right top-menu">
                <li><a class="logout"  style="margin-top: 10px;"  href="{% url 'logout' %}  ">Logout</a></li>
            </ul>

            <ul class="nav pull-right top-menu">
              <p class="logout1" style="color:white; margin-top: 12px; font-size:16px;">{{request.user.username|capfirst }}  </p>
            </ul>
          </div>
        </header>

        <div class = "wrapper" style= "background: url({% static 'images2/bg.png'%}); " />

<!------------------------------------------------------DONEEEEEEEEEEE------------------------------------------->

        <!-- /navbar -->
        <div class="wrapper">
            
            <div class="container">


                    <div class="span9">
                        <div class="content">
                            <div class="btn-controls">
<br><br>
                               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <div class="btn-box-row row-fluid">

                                    <a href="{% url 'HR:main' %}" class="btn-box big span4">  <br><i class="icon-user"></i>
                                    <p class="text-muted">
                                          <br>Attendance</p>
                                    </a><a href="{% url 'task:tasks' %}" class="btn-box big span4"> <br><i class="fas fa-tasks"></i>
                                        <p class="text-muted">
                                           <br> Tasks</p>
                                    </a><a href="http://www.gmail.com" class="btn-box big span4"> <br><i class="icon-envelope"></i>
                                        <p class="text-muted">
                                           <br> Email</p>
                                    </a>
                                </div>
                                <div class="btn-box-row row-fluid">
                                    <a href="{% url 'invoice:inv_opt' %}" class="btn-box big span4"> </br><i class="icon-money"></i>
                                        <p class="text-muted">
                                           <br> Invoice</p>
                                    </a>
                                    <a href="http://www.isf.gov.lb/en" class="btn-box big span4"> </br><i class="icon-book"></i>
                                        <p class="text-muted">
                                            <br> News</p></a>
				                        <a href="https://metropolitansecurity.com.lb/new/" class="btn-box big span4"> <br><i class="icon-globe"></i>
                                        <p class="text-muted">
                                           <br> Website </p></a>


                                </div>

                                    </div>
                                    <div style="width:500px;height:100px;"></div>
                                    <div style="width:500px;height:100px;"></div>
                                    <div style="width:500px;height:100px;"></div>



</div>
                        </div>
</div>
        </div>


    </body>
  